### PR TITLE
Added ability to sort checkout agreements

### PR DESCRIPTION
**Pull request by sreichel**
_... as title says ..._

### CODE REVIEW

**Comment by Schrank** [comment]
Thanks @sreichel! I hope I'll find time this week to check it.

**Comment by sprankhub** [comment]
Thanks for your contribution. Is a certain agreements order required by (German or whatever) law?

**Comment by sreichel** [comment]
There is no requirement ... agreements are displayed in order of entity_id and maybe you want to change this.

**Comment by sreichel** [comment]
Forgot to add field-validation that just allows number input ... i'll update PR later.

**Comment by ADDISON74** [comment]
@sprankhub : personally I am using 3 terms which appear at the end of the checkout process. None of them are having a content because I changed the template, they are only checkboxes. Without this modification provided by @sreichel you cannot arrange your terms if they are more than one. Why I am using more than one checkbox in my store? Because we do not keep inventory in real time. Availability information is "Ask for stock" for some products. Anyone can ask the stock by phone and e-mail and place order. To avoid rumors for products not in stock, a checkbox is asking "Did you check the stock with us?". If they finish the checkout process and the inventory was not checked before, we cannot be blamed. The store has 20.000 products and we have suppliers, some of them are providing real time inventories other not.

**Comment by sprankhub** [comment]
Thanks for your PR @sreichel! I just tested it and implemented two fixes, so that everything works as expected:

- https://github.com/firegento/firegento-magesetup/commit/be79de3378f96c019dfeadd03da66371d957f348: This ensures that the upgrade script is also applied in shops which are already on version `2.4.1`.
- https://github.com/firegento/firegento-magesetup/commit/cd21c3436aba5b000a48f6f8c8293f0769abda37: This ensures that the order is really applied. In my case, the observer method `filterAgreements` did not apply the sort order, because the block type is never `checkout/agreements`.

**Pull request merged**
