### PR TITLE
Feature/bug fix default meta data

### PR DESCRIPTION
**Pull request by riconeitzel**

### CODE REVIEW

**Comment by Schrank** [comment]
What are you doing here @riconeitzel ?

**Comment by riconeitzel** [comment]
MS wrote EVERY category name into meta datas while it makes more sense to only have the meta data of the current root. So you dont get senseless words in the meta data. Came up in a project with better SEO

**Comment by riconeitzel** [comment]
Merge or no merge … that's the question! </shakesbeer>

**Comment by Schrank** [comment]
I think we merge it, any veto can revert it :)

**Pull request merged**
