### PR TITLE
fix issue #159

### PR DESCRIPTION
**Pull request by vmasciotta**
Fix Skip Installation causes 404. 
Tested on 1.9.3.x

### CODE REVIEW

**Comment by Schrank** [comment]
Thank you very much for this PR!

Unfortunately the MageSetupController is part of the Adminhtml, therefore the path is correct. If you get a 404 I'm quite sure you have another Extension which makes this problem.

**Comment by Schrank** [comment]
After reading the issue I'm puzzled. Let me check.

**Comment by Schrank** [comment]
I can't reproduce the problem in the current develop branch.

**Comment by vmasciotta** [comment]
I did install it through composer on 1.9.3.2 using connect20/firegento_magesetup. This just installed the 2.2.2 version. After reading your comments I started to think "maybe there is another version?"  and yes, I didn't notice there was a newer one, so I've upgraded to 2.2.3 and the problem is gone. 

Thank You!

**Pull request closed without merging**
