### PR TITLE
Create new release

### PR DESCRIPTION
**Pull request by avstudnitz**
I think we should merge this and create a new release - many people seem to have used this branch. You opinion @therouv @riconeitzel @Schrank?

### CODE REVIEW

**Comment by Schrank** [comment]
Builds failed, we should fix that. Beside this, the branch is used a lot, therefore I think it is ok.

**Comment by therouv** [comment]
Build fails because travis test script doesn't work. After this is fixed I think we can create a new release.

**Comment by sprankhub** [comment]
This seems to be a MageTestStand issue. Is should be solved as soon as https://github.com/AOEpeople/MageTestStand/pull/12 is merged. I will restart the Travis build as soon as my PR is merged.

**Comment by sprankhub** [comment]
Fixed!

**Comment by riconeitzel** [comment]
wer kann denn ein release-paket machen? @avstudnitz @Schrank @therouv 

Der Branch ist m.E. in Ordnung

**Comment by avstudnitz** [comment]
Are the newly added commits well tested? Otherwise I'd make the release from an older commit like  	4b9898e or 0a83456. 
After merging to master and tagging, I can create the release package for MagentoConnect. I just have to re-setup the packager (https://github.com/Flagbit/Magento-Packager) and run it, probably. Will probably get to it in the upcoming days.

**Comment by riconeitzel** [comment]
@avstudnitz hmmmmm ... "well tested" .... I used it yesterday in a training project and had MageSetup do all it's tasks and after my fixes it worked quite well. But that is not in any meaning a Unit or Integration Test. But I feel confident enough to raise my hand ✋ and say: go for it!

And if it for any reason doesn't work, we'll get aware of that pretty fast 🍌 💻 😈

**Comment by riconeitzel** [comment]
Ich hab mal noch ein wichtiges Ding erledigt. Das schwahl schon länger so vor sich hin und gerade im fiels mir wieder auf die Füße.

**Comment by riconeitzel** [comment]
Here we have the final TGZ (nicely wrapped a ZIP file, so github isn't pissed) …

@avstudnitz @therouv who will upload it? I will merge dev into master next …
 
[FireGento_MageSetup-2.4.0.tgz.zip](https://github.com/firegento/firegento-magesetup/files/916485/FireGento_MageSetup-2.4.0.tgz.zip)

**Pull request merged**
